#app端口
port: 20034
appName: askonce
log:
  level: DEBUG
  stdout: true

##################################
mysql:
  default:
    database: askonce
    addr: ${BACKEND_MYSQL_ADDR}
    user: ${BACKEND_MYSQL_USER}
    password: ${BACKEND_MYSQL_PASSWORD}

redis:
  default:
    addr: ${BACKEND_REDIS_ADDR}
    password: ${BACKEND_REDIS_PASSWORD}

minioConf:
  addr: ${BACKEND_MINIO_ADDR}
  ak: ${BACKEND_MINIO_AK}
  sk: ${BACKEND_MINIO_SK}


esConf:
  addr: ${BACKEND_ES_ADDR}

embeddingModelConf:
  source: skylark
  addr: https://ark.cn-beijing.volces.com
  ak: ${BACKEND_EMBEDDING_MODEL_AK}
  model: ep-20241202225908-h99mn

api:
  jobd:
    # 调用下游的服务名称
    service: jobd
    # 请求完整地址
    domain: ${JOBD_ADDR}
    # 超时配置，time.Duration 类型
    timeout: 60s
    # 重试次数，最多执行retry+1次
    retry: 2

esDbConfig: "{\"mappings_config\":{\"index_name\":\"@indexName@\",\"mappings\":{\"properties\":{\"doc_id\":{\"type\":\"keyword\",\"index\":\"false\"},\"doc_content\":{\"type\":\"text\",\"index\":\"true\",\"analyzer\": \"my_ana\",\"similarity\": \"my_similarity\"},\"emb\":{\"type\":\"dense_vector\",\"dims\":@dimsLength@,\"similarity\":\"cosine\"},\"data_split_id\":{\"type\":\"keyword\",\"index\":\"false\"}}},\"bm25_field\":\"doc_content\",\"emb_fields\":\"emb\"}}"
