#app端口
port: 20034
appName: askonce
log:
  level: DEBUG
  stdout: true
#
##################################
mysql:
  default:
    database: askonce
    addr: "127.0.0.1:3306"
    user: "root"
    password: "123456"

redis:
  default:
    addr: "127.0.0.1::6379"
    password: ""
    db: 1

minioConf:
  addr: http://127.0.0.1:9000
  ak: 9OzakHogqTW8KBunbOaq
  sk: IvbG5GYw7EwwIR5JWwmQ38YNGQPqtYSmSY02KwaA


esConf:
  addr: http://127.0.0.1:30502

api:
  jobd:
    # 调用下游的服务名称
    service: jobd
    # 请求完整地址
    domain: http://127.0.0.1:20033
    # 超时配置，time.Duration 类型
    timeout: 600s
    # 重试次数，最多执行retry+1次
    retry: 2

esDbConfig: "{\"mappings_config\":{\"index_name\":\"${indexName}\",\"mappings\":{\"properties\":{\"doc_id\":{\"type\":\"keyword\",\"index\":\"false\"},\"doc_content\":{\"type\":\"text\",\"index\":\"true\",\"analyzer\": \"my_ana\",\"similarity\": \"my_similarity\"},\"emb\":{\"type\":\"dense_vector\",\"dims\":1024,\"similarity\":\"cosine\"},\"data_split_id\":{\"type\":\"keyword\",\"index\":\"false\"}}},\"bm25_field\":\"doc_content\",\"emb_fields\":\"emb\"}}"
