services:
  dispatch:
    build:
      context: ../server/dispatch
      dockerfile: Dockerfile
    ports:
      - "20033:8080"
    volumes:
      - ./conf/dispatch:/app/conf/mount
    restart: unless-stopped