services:
  dispatch:
    container_name: dispatch
    build:
      context: ../server/dispatch
      dockerfile: Dockerfile
    ports:
      - "20033:8080"
    volumes:
      - ./conf/dispatch:/app/conf/mount
    restart: unless-stopped
  mysql:
    restart: always
    image: mysql:8.0.35
    container_name: mysql
    environment:
      TZ: 'Asia/Shanghai'
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_ROOT_HOST: '%'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./conf/mysql:/etc/mysql
    ports:
      - 3306:3306
  redis:
    restart: always
    image: redis:alpine
    container_name: redis
    volumes:
      - ./conf/redis/redis.conf:/etc/redis/redis.conf
      - ./data/redis:/data
    ports:
      - 6379:6379