services:
  jobd:
    build:
      context: ../server/jobd
      dockerfile: Dockerfile
    container_name: askonce-jobd
    ports:
      - "20033:8080"
    volumes:
      - ./conf/jobd:/app/conf/mount
    restart: unless-stopped