
services:
  jobd:
    extends:
      file: backend-docker-compose.yml
      service: jobd
    depends_on:
      - mysql
      - redis
  backend:
    extends:
      file: backend-docker-compose.yml
      service: backend
    depends_on:
      - mysql
      - redis
  askonce-nginx:
    extends:
      file: web-docker-compose.yml
      service: askonce-nginx
  mysql:
    extends:
      file: db-docker-compose.yml
      service: mysql
  redis:
    extends:
      file: db-docker-compose.yml
      service: redis
  minio:
    extends:
      file: db-docker-compose.yml
      service: minio
  askonce-es1:
    extends:
      file: es-docker-compose.yml
      service: askonce-es1
  askonce-es2:
    extends:
      file: es-docker-compose.yml
      service: askonce-es2
  askonce-es3:
    extends:
      file: es-docker-compose.yml
      service: askonce-es3
  askonce-es-dashboard:
    extends:
      file: es-docker-compose.yml
      service: askonce-es-dashboard
