services:
  askonce-es1:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    container_name: askonce-es1
    ports:
      - 20004:9200
    environment:
      - cluster.name=askonce
      - node.name=askonce-es1
      - bootstrap.memory_lock=true
      - ELASTIC_PASSWORD=${ES_PASSWORD}
      - xpack.security.enabled=false
      - TAKE_FILE_OWNERSHIP=true
      - "ES_JAVA_OPTS=-Xms4096m -Xmx4096m"
      - discovery.seed_hosts=askonce-es1,askonce-es2,askonce-es3
      - cluster.initial_master_nodes=askonce-es1,askonce-es2,askonce-es3
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${ES_DATA_DIR}/node1:/usr/share/elasticsearch/data
      - ${ES_CONF_DIR}/plugins:/usr/share/elasticsearch/plugins
      - ${ES_CONF_DIR}/stopwords:/usr/share/elasticsearch/config/stopwords
  askonce-es2:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    container_name: askonce-es2
    environment:
      - cluster.name=askonce
      - node.name=askonce-es2
      - bootstrap.memory_lock=true
      - ELASTIC_PASSWORD=${ES_PASSWORD}
      - TAKE_FILE_OWNERSHIP=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms4096m -Xmx4096m"
      - discovery.seed_hosts=askonce-es1,askonce-es2,askonce-es3
      - cluster.initial_master_nodes=askonce-es1,askonce-es2,askonce-es3
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${ES_DATA_DIR}/node2:/usr/share/elasticsearch/data
      - ${ES_CONF_DIR}/plugins:/usr/share/elasticsearch/plugins
      - ${ES_CONF_DIR}/stopwords:/usr/share/elasticsearch/config/stopwords
  askonce-es3:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    container_name: askonce-es3
    environment:
      - cluster.name=askonce
      - node.name=askonce-es3
      - bootstrap.memory_lock=true
      - ELASTIC_PASSWORD=${ES_PASSWORD}
      - TAKE_FILE_OWNERSHIP=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms4096m -Xmx4096m"
      - discovery.seed_hosts=askonce-es1,askonce-es2,askonce-es3
      - cluster.initial_master_nodes=askonce-es1,askonce-es2,askonce-es3
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${ES_DATA_DIR}/node3:/usr/share/elasticsearch/data
      - ${ES_CONF_DIR}/plugins:/usr/share/elasticsearch/plugins
      - ${ES_CONF_DIR}/stopwords:/usr/share/elasticsearch/config/stopwords
  askonce-es-dashboard:
    restart: always
    image: docker.elastic.co/kibana/kibana:8.15.3
    container_name: askonce-es-dashboard
    ports:
      - 20005:5601
    environment:
      - ELASTICSEARCH_HOSTS=["http://askonce-es1:9200"]
      - I18N_LOCALE=zh-CN
      - ELASTICSEARCH_USERNAME='elastic'
      - ELASTICSEARCH_PASSWORD=${ES_PASSWORD}

