version: "3.7"

services:
  atom_app_askonce_simple_qa_construct_0:
    container_name: atom_app_askonce_simple_qa_construct_0
    build:
      context: ../
      dockerfile: AskOnce/algorithm/services/docker_files/Dockerfile
      network: host
    image: askonce_llm_service_image
    network_mode: host
    shm_size: '4gb'
    command: /bin/bash -c "python askonce/main.py "
    tty: true
    environment:
      - LANG=C.UTF-8
    restart: "no"
