services:
  askonce_answer_by_documents_0:
    container_name:   askonce_answer_by_documents_0
    build:
      context: ../../
      dockerfile: AskOnce/algorithm/services/docker_files/Dockerfile
      network: host
    image: askonce_llm_service_image
    network_mode: host
    shm_size: '4gb'
    command: /bin/bash -c "python answer_by_documents/answer_by_documents.py --jobdurl ${JOBD_URL} --tasktype answer_by_documents --worker_name answer_by_documents_0 --api_key ${LLM_API_KEY} --model_name ${LLM_MODEL_NAME} --platform_api_url ${LLM_API_URL} "
    tty: true
    environment:
      - LANG=C.UTF-8
    restart: "no"

  askonce_data_convert_0:
    container_name:   askonce_data_convert_0
    build:
      context: ../../
      dockerfile: AskOnce/algorithm/services/docker_files/Dockerfile
      network: host
    image: askonce_llm_service_image
    network_mode: host
    shm_size: '4gb'
    command: /bin/bash -c "python data_convert/data_convert.py --jobdurl ${JOBD_URL} --tasktype convert_file_to_text --worker_name convert_file_to_text_0 --correct_dict_path /home/workspace/AskOnce/assets/dict.json "
    tty: true
    volumes:
      - ${CONVERT_CACHE}:${CONVERT_CACHE}
    environment:
      - LANG=C.UTF-8
      - CONVERT_CACHE=${CONVERT_CACHE}
    restart: "no"

  askonce_generate_outlines_0:
    container_name:   askonce_generate_outlines_0
    build:
      context: ../../
      dockerfile: AskOnce/algorithm/services/docker_files/Dockerfile
      network: host
    image: askonce_llm_service_image
    network_mode: host
    shm_size: '4gb'
    command: /bin/bash -c "python generate_outlines/generate_outlines.py --jobdurl ${JOBD_URL} --tasktype generate_outlines --worker_name generate_outlines_0 --api_key ${LLM_API_KEY} --model_name ${LLM_MODEL_NAME} --platform_api_url ${LLM_API_URL} "
    tty: true
    environment:
      - LANG=C.UTF-8
    restart: "no"
  
  askonce_result_add_reference_0:
    container_name:   askonce_result_add_reference_0
    build:
      context: ../../
      dockerfile: AskOnce/algorithm/services/docker_files/Dockerfile
      network: host
    image: askonce_llm_service_image
    network_mode: host
    shm_size: '4gb'
    command: /bin/bash -c "python result_add_reference/result_add_reference.py --jobdurl ${JOBD_URL} --tasktype result_add_reference --worker_name result_add_reference_0 --stop_word_file /home/workspace/AskOnce/assets/stopwords.txt "
    tty: true
    environment:
      - LANG=C.UTF-8
    restart: "no"

  askonce_split_question_0:
    container_name:   askonce_split_question_0
    build:
      context: ../../
      dockerfile: AskOnce/algorithm/services/docker_files/Dockerfile
      network: host
    image: askonce_llm_service_image
    network_mode: host
    shm_size: '4gb'
    command: /bin/bash -c "python split_question/split_question.py --jobdurl ${JOBD_URL} --tasktype split_question --worker_name split_question_0 --api_key ${LLM_API_KEY} --model_name ${LLM_MODEL_NAME} --platform_api_url ${LLM_API_URL} "
    tty: true
    environment:
      - LANG=C.UTF-8
    restart: "no"

  askonce_search_engine_insert_0:
    container_name:   askonce_search_engine_insert_0
    build:
      context: ../../
      dockerfile: AskOnce/algorithm/services/docker_files/Dockerfile
      network: host
    image: askonce_llm_service_image
    network_mode: host
    shm_size: '4gb'
    command: /bin/bash -c "python search_engine/insert.py --jobdurl ${JOBD_URL} --tasktype search_engine_insert --worker_name search_engine_insert_0 --es_address ${ES_ADDRESS} --es_username ${ES_USERNAME} --es_password ${ES_PASSWORD} --es_setting_path /home/workspace/AskOnce/assets/es_setting.json "
    tty: true
    environment:
      - LANG=C.UTF-8
    restart: "no"

  askonce_search_engine_delete_0:
    container_name:   askonce_search_engine_delete_0
    build:
      context: ../../
      dockerfile: AskOnce/algorithm/services/docker_files/Dockerfile
      network: host
    image: askonce_llm_service_image
    network_mode: host
    shm_size: '4gb'
    command: /bin/bash -c "python search_engine/delete.py --jobdurl ${JOBD_URL} --tasktype search_engine_delete --worker_name search_engine_delete_0 --es_address ${ES_ADDRESS} --es_username ${ES_USERNAME} --es_password ${ES_PASSWORD} --es_setting_path /home/workspace/AskOnce/assets/es_setting.json "
    tty: true
    environment:
      - LANG=C.UTF-8
    restart: "no"

  askonce_search_engine_search_0:
    container_name:   askonce_search_engine_search_0
    build:
      context: ../../
      dockerfile: AskOnce/algorithm/services/docker_files/Dockerfile
      network: host
    image: askonce_llm_service_image
    network_mode: host
    shm_size: '4gb'
    command: /bin/bash -c "python search_engine/search.py --jobdurl ${JOBD_URL} --tasktype search_engine_search --worker_name search_engine_search_0 --es_address ${ES_ADDRESS} --es_username ${ES_USERNAME} --es_password ${ES_PASSWORD} --es_setting_path /home/workspace/AskOnce/assets/es_setting.json "
    tty: true
    environment:
      - LANG=C.UTF-8
    restart: "no"
