services:
  askonce-nginx:
    container_name: askonce-nginx
    build:
      context: ../web
      dockerfile: ../web/Dockerfile
    ports:
      - "20010:8080"
    volumes:
      - ../web/askonce.conf:/etc/nginx/conf.d/default.conf
      - ../web/dist:/usr/share/nginx/html/dist
