#app端口
port: 8080
appName: jobd
log:
  level: INFO
  stdout: true
  logToFile: true

redis:
  default:
    addr: ${BACKEND_REDIS_ADDR}
    password: ${BACKEND_REDIS_PASSWORD}

mysql:
  default:
    database: jobd
    addr: ${BACKEND_MYSQL_ADDR}
    user: ${BACKEND_MYSQL_USER}
    password: ${BACKEND_MYSQL_PASSWORD}
