#!/bin/bash

# 需要打包的服务文件名，标准的服务是放在相同名称文件夹下的，如：document_split/document_split.py
files=("document_split" "answer_by_documents")

# Loop through the array and execute pyinstaller for each file
for file in "${files[@]}"; do
  echo "开始构建服务 $file..."
  pyinstaller --onefile --noconfirm --clean --distpath ./bin/ --add-data "../algorithm:AskOnce/algorithm" --name "$file" "services/$file/$file.py"
  # Clean up temporary files generated by PyInstaller
  echo "清理临时文件，服务： $file..."
  rm -rf build/  # Remove the build directory
  rm -rf "$file.spec"  # Remove the spec file created by PyInstaller
  rm -rf __pycache__/  # Remove any __pycache__ directories if present
  echo "服务 $file 构建完成."
done
