services:
  askonce_algorithm_build:
    container_name: askonce_algorithm_build
    build:
      context: .
      dockerfile: Dockerfile_build
    volumes:
      - ./bin:/home/workspace/AskOnce/algorithm/build
    command: /bin/bash -c "/home/workspace/AskOnce/algorithm/build.sh && exit"  # 执行构建任务后退出
  askonce_algorithm:
    build:
      context: .
      dockerfile: Dockerfile_run
    depends_on:
      - askonce_algorithm_build
    env_file:
      - ./../deploy/.env
    volumes:
      - ./bin:/home/workspace/AskOnce/algorithm/
      - /data:/data
    restart: unless-stopped
    network_mode: host
    shm_size: '4gb'