version: '3.8'

services:
  askonce:
    container_name: askonce-nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "20010:8080"
    volumes:
      - ./askonce.conf:/etc/nginx/conf.d/askonce.conf
      - ./dist:/usr/share/nginx/html/dist
